### ISSUE TITLE
Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.

### ISSUE THREAD

**Issue by shiyuhang0** [cloudflare/next-on-pages#54]
I am using nextjs and prisma data proxy to connect to a database.
Then I deploy to cloudflare pages but failed with `Script startup exceeded CPU time limit`.

I don't know if it is the problem of my project or the work_js generated by next-on-pages.
 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/52435083/212228256-662e499c-baa3-4489-8eb7-5f3afc1bb9ae.png">

**Comment by mihazs** [comment]
I'm having the same issue right now, i'm not able to update my application because of that.

In my case, the `_worker.js` file inside `.vercel/output/static` folder, has `7.2MB`, which is very huge for a worker script.

According with : https://developers.cloudflare.com/workers/platform/limits/#worker-startup-time
```
Script size can impact startup because there’s more code to parse and evaluate.
```
In my tests, the `_worker.js` file easily increases a lot the size in every new build with new features, so the script startup will exceed CPU time limit all the time.

For me, this is a deal breaker. I came to the conclusion that cloudflare pages and next.js only works for tiny projects at this moment. Right now, I'm working to get my project out of the cloudflare and considering Vercel, netlify or [open-next](https://github.com/serverless-stack/open-next) for deploy to AWS. 

If you want a fast solution, probably cloudflare wouldn't fit :/

**Comment by saaymeen** [comment]
Sharing this experience with a very small project, 5 pages, not many additional dependencies and 2 pages using little data from getServerSideProps.

**Comment by xMuratY** [comment]
I just created a layout component (just some html no server side things) and then created dummy pages with the calling layout. After duplicating the pages this problem appeared. Can publish with removing some of the dummies.

**Comment by Rigo-m** [comment]
Why isn't the CPU limit following the bundled/unbounded rules?
I.e.: I tried changing to unbounded mode (30s startup time limit vs 50ms CPU Time Limit), but I got the same error after 2 seconds.

**Comment by nitaking** [comment]
@GregBrimble 

> If you can, try to move any work you do into request handlers rather than having it in global scope, as this moves the work from startup time to request time which may help here.

Can you give us a specific example?

I understand why this is closed, but it has become an immediate problem faced by sites using cloudflare pages and Nextjs and is an issue that should be addressed quickly to resolve.

Cloudflare team should provide some kind of concrete solution.

**Comment by dario-piotrowicz** [comment]
@nitaking Yeah this is a real issue and something that I believe very often developers can't do much about (especially if they include third party code which can do things at startup anyways).

We've actually already got a solution for this and we should release it soon, but before we can do that some changes need to be made in [wrangler](https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler) and I believe Greg is looking into that.

The solution will be next-on-pages splitting the code appropriately and lazy loading route code so that it is run only when needed resulting in a much lighter startup processing, so from a developer point of view you will hopefully only have to upgrade the next-on-pages package and things should just work 🙂👍

**Comment by ynishimura** [comment]
I am experiencing the same problem. Is there a workaround?

**Comment by Rigo-m** [comment]
> We've actually already got a solution for this and we should release it soon, but before we can do that some changes need to be made in [wrangler](https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler) and I believe Greg is looking into that.

Since this problem is present in other metaframeworks as well (e.g.: nuxt3 with nitro), would you mind sharing your findings so that it's possible to pass on these improvements in these other metaframeworks as well?

**Comment by uglyrobot** [comment]
Blocked me from using Pages today as well. Off to Vercel...

**Comment by dario-piotrowicz** [comment]
> Since this problem is present in other metaframeworks as well (e.g.: nuxt3 with nitro), would you mind sharing your findings so that it's possible to pass on these improvements in these other metaframeworks as well?

@Rigo-m thanks a lot for the interest! 😃 and sorry for the late reply 😓 anyways I'll share the strategy in details when we add it to the project

We're also planning to contact and try to work with metaframework authors to help in this, although we've seen that many metaframeworks will need to change how they bundle the _worker before they can apply such type of strategy (it also depends on how the metaframework itself works and how it splits its code).

Anyways the strategy is simple, basically wrangler is introducing the ability to use dynamic imports, once we have those, instead of bundling everything together (which causes extra code to unnecessarily run) we add dynamic imports so that the code is evaluated and run only when actually used.

In next-on-pages basically the idea is to have a basic worker which simply acts at the next server/router (with just the basic logic, so it's going to be much faster), then when it needs to use a route, only at that point it dynamically imports that route's code.

<details>
<summary>Example</summary>

So for example let's say your app has `routeA`, `routeB` and `apiRouteX` and say `routeA` uses `libA`, `routeB` uses `libB` and `apiRouteX` uses `libX` all of which do some setup work

now we kind of take all of that js code and bundle it together, so all the setup work for `libA`, `libB` and `libX` is always run for every request

with dynamic imports, if you'll request `routeB` the worker won't load the `libA` and `libX` code at all, just the `libB` one with its setup work, so overall every request should be much faster (making it more difficult to hit the startup CPU time limit) 
</details>

I hope the above helps, as I said I'll probably make this much more clear and provide a more detailed description of this when we actually add it to the project 🙂 (which should hopefully be pretty soon)

**Comment by Rigo-m** [comment]
This is extremely encouraging. And extremely is an undestatement.
We want to ditch netlify for cloudflare pages but the thing that at some point the app breaks for being too large has been a huge no-no for now, because it's too scary. Knowing that this issue is being tackled is a thing of pure joy. Paging @danielroe on this, hoping that Nitro will be ready for this change

Eagerly waiting to hear when this is finished, thanks a lot for your time!

**Comment by danielroe** [comment]
@Rigo-m Thanks for the ping. We are in contact now 😊

**Comment by lourou** [comment]
I got the same error. I only have one basic hello world /api function in a nextjs@13 project, that then fails to build on Cloudflare pages: `Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.`

**Comment by olajiredominic** [comment]
Similar experience
`10:58:34.092 | ⚡️ Completed `npx vercel build`.
10:58:37.268 | ⚡️ Generated '.vercel/output/static/_worker.js'.
10:58:37.345 | Finished
10:58:37.345 | Found _worker.js in output directory. Uploading.
10:58:38.453 | ✨ Compiled Worker successfully
10:58:38.530 | Found _routes.json in output directory. Uploading.
10:58:38.592 | Validating asset output directory
10:58:39.512 | Deploying your site to Cloudflare's global network...
10:58:42.159 | Parsed 1 valid header rule.
10:58:43.359 | Uploading... (84/86)
10:58:43.972 | Uploading... (85/86)
10:58:44.032 | Uploading... (86/86)
10:58:44.032 | ✨ Success! Uploaded 2 files (84 already uploaded) (1.20 sec)
10:58:44.032 |  
10:58:44.314 | ✨ Upload complete!
10:58:46.532 | Success: Assets published!
10:58:48.503 | Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.
`

**Comment by bruce-shi** [comment]
https://github.com/cloudflare/next-on-pages/pull/191
https://github.com/cloudflare/workers-sdk/pull/2966

Since above two PR are still pending to merge, If you are in a hurry you can setup a GitHub action to manually deploy to CloudFlare pages.

This is an example of Github Workflow file.
```
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      # Run your project's build step
      - name: Build
        run: yarn install && npx https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/4786008794/npm-package-next-on-pages-191
      - name: Publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/prs/2966/npm-package-wrangler-2966 pages publish .vercel/output/static --project-name=$PROJECT_NAME --branch=$GITHUB_REF_NAME
```
The trick here is to use the preview version of `wrangler` and `next-on-pages` from the following PR.
https://github.com/cloudflare/next-on-pages/pull/191
https://github.com/cloudflare/workers-sdk/pull/2966

Follow this guide to set up your account id and api token:
https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/
