### ISSUE TITLE
[🐛 Bug]: nextjs local preview succeeded, deployment succeeded, but no deployment was shown

### ISSUE THREAD

**Issue by hehehai** [cloudflare/next-on-pages#740]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: x64
        Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64
        CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
        Memory: 32 GB
        Shell: /bin/zsh
Package Manager Used: npm (10.1.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.11.0
        vercel: N/A
        next: N/A

### Description

developed the nextjs project, using pages deployment, the first deployment was successful, but after my subsequent modifications, the deployment was successful, but accessing pages failed

<img width="1185" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/12692552/720a5326-575d-4480-a3ce-09b1405645bf">

### Reproduction

https://github.com/hehehai/at4-kit

```toml
name = "at4-start"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_xx"
CLERK_SECRET_KEY = "sk_test_xx"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prisma-demo-db"
database_id = "xx"
```

```json
"pages:build": "npx @cloudflare/next-on-pages",
"preview": "npm run pages:build && wrangler pages dev .vercel/output/static",
"deploy": "npm run pages:build && wrangler pages deploy .vercel/output/static",
"build-cf-types": "wrangler types --env-interface CloudflareEnv env.d.ts"
```

### Pages Deployment Method

None

### Pages Deployment ID

at4-start

### Would you like to help?

- [ ] Would you like to help fixing this bug?
